{% set name = "crepe" %}
{% set version = "0.0.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: af81c6ef6350ab5bcd11da036f2198158df8d84ef5ee34f6d5841d57668aaa61

build:
  noarch: python
  number: 0
  entry_points:
    - crepe=crepe.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - h5py <3.0.0,>=2.7.0
    - hmmlearn <0.3.0,>=0.2.0
    - imageio >=2.3.0
    - matplotlib-base >=2.1.0
    - numpy >=1.14.0
    - resampy <0.3.0,>=0.2.0
    - scikit-learn >=0.16
    - scipy >=1.0.0

test:
  imports:
    - crepe
  commands:
    - crepe --help

about:
  home: https://github.com/marl/crepe
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: CREPE pitch tracker
  doc_url: https://pypi.org/project/crepe/
  dev_url: https://github.com/marl/crepe

extra:
  recipe-maintainers:
    - mxr-conda
    - oblute
    - rluria14
    - ndmaxar
